### ISSUE TITLE
Guidance on scope of data collected

### ISSUE THREAD

**Issue by jraller** [newsdev/nyt-forcible-entry#1]
Is there any guidance on how to go about adding additional data columns? Right now the data can't answer several questions:

- if deceased civilian was the target of the warrant, or a bystander
- age of civilian
- purpose of warrant
- single department, or multi-jurisdictional task force. Were the police on scene all part of a single department, or were they from different departments
- if officer death was by friendly fire or as a result of exchange with civilian
- if any animals were killed - anecdotally usually dogs as part of the process of serving the warrant
- type of building - single family home, apartment, duplex, etc

**Comment by gabrieldance** [comment]
Feel free to fork this dataset and add additional columns.
